#!/usr/bin/env bash
#Write a Bash script that displays: To infinity and beyond indefinitely
#With a sleep 2 in between each iteration and I am invincible!!! when receiving a SIGTERM signal

msg()
{
    echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
